/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutUtilitiesRouteImport } from './routes/_layout.utilities'
import { Route as LayoutRequestsRouteImport } from './routes/_layout.requests'
import { Route as LayoutPropertyRouteImport } from './routes/_layout.property'
import { Route as LayoutProfileRouteImport } from './routes/_layout.profile'
import { Route as LayoutPaymentsRouteImport } from './routes/_layout.payments'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout.notifications'
import { Route as LayoutMaintenanceRouteImport } from './routes/_layout.maintenance'
import { Route as LayoutDocumentsRouteImport } from './routes/_layout.documents'
import { Route as LayoutContractRouteImport } from './routes/_layout.contract'
import { Route as LayoutBillingRouteImport } from './routes/_layout.billing'

const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUtilitiesRoute = LayoutUtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRequestsRoute = LayoutRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPropertyRoute = LayoutPropertyRouteImport.update({
  id: '/property',
  path: '/property',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPaymentsRoute = LayoutPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMaintenanceRoute = LayoutMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDocumentsRoute = LayoutDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContractRoute = LayoutContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBillingRoute = LayoutBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/splash': typeof SplashRoute
  '/billing': typeof LayoutBillingRoute
  '/contract': typeof LayoutContractRoute
  '/documents': typeof LayoutDocumentsRoute
  '/maintenance': typeof LayoutMaintenanceRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/payments': typeof LayoutPaymentsRoute
  '/profile': typeof LayoutProfileRoute
  '/property': typeof LayoutPropertyRoute
  '/requests': typeof LayoutRequestsRoute
  '/utilities': typeof LayoutUtilitiesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/splash': typeof SplashRoute
  '/billing': typeof LayoutBillingRoute
  '/contract': typeof LayoutContractRoute
  '/documents': typeof LayoutDocumentsRoute
  '/maintenance': typeof LayoutMaintenanceRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/payments': typeof LayoutPaymentsRoute
  '/profile': typeof LayoutProfileRoute
  '/property': typeof LayoutPropertyRoute
  '/requests': typeof LayoutRequestsRoute
  '/utilities': typeof LayoutUtilitiesRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/splash': typeof SplashRoute
  '/_layout/billing': typeof LayoutBillingRoute
  '/_layout/contract': typeof LayoutContractRoute
  '/_layout/documents': typeof LayoutDocumentsRoute
  '/_layout/maintenance': typeof LayoutMaintenanceRoute
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/payments': typeof LayoutPaymentsRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/property': typeof LayoutPropertyRoute
  '/_layout/requests': typeof LayoutRequestsRoute
  '/_layout/utilities': typeof LayoutUtilitiesRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/splash'
    | '/billing'
    | '/contract'
    | '/documents'
    | '/maintenance'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/property'
    | '/requests'
    | '/utilities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/forgot-password'
    | '/splash'
    | '/billing'
    | '/contract'
    | '/documents'
    | '/maintenance'
    | '/notifications'
    | '/payments'
    | '/profile'
    | '/property'
    | '/requests'
    | '/utilities'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/auth'
    | '/forgot-password'
    | '/splash'
    | '/_layout/billing'
    | '/_layout/contract'
    | '/_layout/documents'
    | '/_layout/maintenance'
    | '/_layout/notifications'
    | '/_layout/payments'
    | '/_layout/profile'
    | '/_layout/property'
    | '/_layout/requests'
    | '/_layout/utilities'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SplashRoute: typeof SplashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/utilities': {
      id: '/_layout/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof LayoutUtilitiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/requests': {
      id: '/_layout/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof LayoutRequestsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/property': {
      id: '/_layout/property'
      path: '/property'
      fullPath: '/property'
      preLoaderRoute: typeof LayoutPropertyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/payments': {
      id: '/_layout/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof LayoutPaymentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/maintenance': {
      id: '/_layout/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof LayoutMaintenanceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/documents': {
      id: '/_layout/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof LayoutDocumentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contract': {
      id: '/_layout/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof LayoutContractRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/billing': {
      id: '/_layout/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof LayoutBillingRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBillingRoute: typeof LayoutBillingRoute
  LayoutContractRoute: typeof LayoutContractRoute
  LayoutDocumentsRoute: typeof LayoutDocumentsRoute
  LayoutMaintenanceRoute: typeof LayoutMaintenanceRoute
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutPaymentsRoute: typeof LayoutPaymentsRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutPropertyRoute: typeof LayoutPropertyRoute
  LayoutRequestsRoute: typeof LayoutRequestsRoute
  LayoutUtilitiesRoute: typeof LayoutUtilitiesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBillingRoute: LayoutBillingRoute,
  LayoutContractRoute: LayoutContractRoute,
  LayoutDocumentsRoute: LayoutDocumentsRoute,
  LayoutMaintenanceRoute: LayoutMaintenanceRoute,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutPaymentsRoute: LayoutPaymentsRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutPropertyRoute: LayoutPropertyRoute,
  LayoutRequestsRoute: LayoutRequestsRoute,
  LayoutUtilitiesRoute: LayoutUtilitiesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SplashRoute: SplashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
